spring:
  profiles:
    active: study

---
spring:
  config:
    activate:
      on-profile: study
  security:
    user:
      name: user
      password: 1111
---
spring:
  config:
    activate:
      on-profile: test

---
logging:
  level:
    root: info
    me.kenux.springsecurity: debug